name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    services:
      mockserver:
        image: mockserver/mockserver
        ports:
          - 1080:1080

    steps:
      - uses: actions/checkout@v1

      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart pub run test
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          UNSPLASH_SECRET_KEY: ${{ secrets.UNSPLASH_SECRET_KEY }}

      - name: Run example
        run: dart example/lib/main.dart
        env:
          UNSPLASH_ACCESS_KEY: ${{ secrets.UNSPLASH_ACCESS_KEY }}
          UNSPLASH_SECRET_KEY: ${{ secrets.UNSPLASH_SECRET_KEY }}
